name: LLMOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Variables you may want to customize
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app
  DEPLOYMENT_NAME: gpt-huggingface
  CONTAINER_NAME: gptcontainer
  NAMESPACE: default

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Save image tag
        id: img
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  trivy-scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: build-and-push
    timeout-minutes: 10

    steps:
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Load kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config   # <-- Secret: your kubeconfig content

      - name: Update Deployment image
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.CONTAINER_NAME }}=${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }} \
            -n $NAMESPACE

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n $NAMESPACE
